version: '3.7'
services:
  opencloud:
    image: nextcloud:latest
    container_name: opencloud
    restart: unless-stopped
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ${APP_DATA_DIR}/data:/var/www/html
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
